name: Deploy

on:
  push:
    branches: ["main"]
    paths:
      - "src/**/*"
      - wrangler.toml

  workflow_dispatch:

jobs:
  build:
    uses: ./.github/workflows/main.yml

  deploy:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: read
      deployments: write
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: artifact
          path: .
      - run: find .
      - name: Deploy
        uses: cloudflare/wrangler-action@v3
        with:
          wranglerVersion: "3.47.1"
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          command: pages deploy
